export const FETCH_CLOTHES_SUCCESS = 'FETCH_CLOTHES_SUCCESS';
export const FETCH_CLOTHES_FAILURE = 'FETCH_CLOTHES_FAILURE';
export const FETCH_CLOTHES_REQUEST = 'FETCH_CLOTHES_REQUEST';
export const FETCH_CLOTH_ITEM_SUCCESS = 'FETCH_CLOTH_ITEM_SUCCESS';
export const FETCH_CLOTH_ITEM_FAILURE = 'FETCH_CLOTH_ITEM_FAILURE';
export const FETCH_CLOTH_ITEM_REQUEST = 'FETCH_CLOTH_ITEM_REQUEST';